version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install awscli

  pre_build:
    commands:
      - echo "Executing pre-build commands..."

  build:
    commands:
      - echo "Building CloudFormation templates..."
      - aws cloudformation validate-template --template-body file://template.yaml

  post_build:
    commands:
      - echo "Executing post-build commands..."

